/**
 * BUFF FPGA Inference — Type definitions and configuration constants.
 *
 * This header is generated by export_conifer.py for a specific trained model.
 * Default values below correspond to a d=4, N=30 Euler configuration.
 * The export script replaces the ${...} tokens with concrete values.
 */
#ifndef BUFF_TYPES_H
#define BUFF_TYPES_H

#include <ap_fixed.h>

// ── Model configuration ──────────────────────────────────────────────
// These are overwritten by export_conifer.py for a specific model.
#ifndef N_FEATURES
#define N_FEATURES 4
#endif
#ifndef N_STEPS
#define N_STEPS 30
#endif
#ifndef N_TREES
#define N_TREES 100
#endif
#ifndef MAX_DEPTH
#define MAX_DEPTH 4
#endif

// Derived constants
static const int N_INTERNAL_NODES = (1 << MAX_DEPTH) - 1;  // 2^depth - 1
static const int N_LEAVES = 1 << MAX_DEPTH;                 // 2^depth

// ── Fixed-point types ────────────────────────────────────────────────
// data_t:  feature values and BDT thresholds  (16 bits, 6 integer)
// score_t: BDT leaf scores                    (16 bits, 6 integer)
// accum_t: wider accumulator for ODE step     (24 bits, 12 integer)
typedef ap_fixed<16, 6> data_t;
typedef ap_fixed<16, 6> score_t;
typedef ap_fixed<24, 12> accum_t;

// ── Step size ────────────────────────────────────────────────────────
// h = 1 / (N_STEPS - 1), pre-computed for Euler integration.
// For N_STEPS=30: h ~= 0.03448
static const data_t STEP_H = data_t(1.0 / (N_STEPS - 1));

// ── Feature array type ───────────────────────────────────────────────
typedef data_t feature_vec_t[N_FEATURES];

// ── Scaler parameters ────────────────────────────────────────────────
// Forward MinMax scaler:  x_scaled = x * SCALE + OFFSET
// Inverse:                x_orig   = x_scaled * INV_SCALE + INV_OFFSET
//
// Generated by export_conifer.py from sklearn MinMaxScaler state.
// Default: identity (no scaling), to allow standalone C simulation.
extern const data_t SCALE[N_FEATURES];
extern const data_t OFFSET[N_FEATURES];
extern const data_t INV_SCALE[N_FEATURES];
extern const data_t INV_OFFSET[N_FEATURES];

// ── BDT tree parameter arrays ────────────────────────────────────────
// Stored per-feature, indexed by [timestep][tree][node].
// Generated by export_conifer.py from conifer-converted XGBoost models.
//
// threshold:   comparison values at internal nodes
// children_left / children_right:  child node indices (for generic traversal)
// feature_idx: which input feature to compare at each internal node
// leaf_value:  score at each leaf (summed across all trees)
//
// These are declared extern; definitions are in the generated
// bdt_params.h (included by bdt_ensemble.h).
extern const data_t   bdt_threshold[N_FEATURES][N_STEPS][N_TREES][N_INTERNAL_NODES];
extern const int       bdt_feature_idx[N_FEATURES][N_STEPS][N_TREES][N_INTERNAL_NODES];
extern const score_t  bdt_leaf_value[N_FEATURES][N_STEPS][N_TREES][N_LEAVES];

// Tolerance for testbench comparison (quantization error budget)
static const float TOLERANCE = 0.05f;

#endif  // BUFF_TYPES_H
